### PR TITLE
Added Cake.Recipe to build process

### PR DESCRIPTION
**Pull request by gep13**
Relates to #9 and #17

### CODE REVIEW

**Comment by gep13** [comment]
@wwwlicious okay, I "think" I have done everything that I wanted to in this PR.

Can you review it and let me know what you think about the changes.  And if you are happy, we can discuss the release process (some of which is documented [here](https://cake-contrib.github.io/Cake.Recipe/docs/)) in order to get a new version out.

Thanks!

**Comment by wwwlicious** [comment]
@gep13 I'll check it out tonight, thanks

**Comment by wwwlicious** [comment]
@gep13 Looks good, you want to walk me through the release process?

**Comment by gep13** [comment]
@wwwlicious just away to sign off for the night, but I will write some quick notes here tomorrow.

**Comment by gep13** [comment]
@wwwlicious so the guts of the release process is documented here:

https://cake-contrib.github.io/Cake.Recipe/docs/usage/creating-release

But let's go through it specifically for where this repo currently is.  This is what I would be doing...

- Merge the PR.
- Close issues #9 and #17 
- Create a release branch `release/1.1.0
- Add environment variables as described above for creating GitHub release
- Execute `.\build.ps1 -target releasenotes` to generate draft GitHub release and verify that it contains everything you expect
- Add any additional documentation that you want included/updated
- Execute `.\build.ps1 -target preview` and open http://localhost:5080/Cake.Incubator and make sure everything is as you want it to be
- Commit and changes
- Checkout master branch and merge release branch `git merge --no-ff release/1.1.0
- Push changes
- Watch AppVeyor to make sure everything works as expected
- Go to the GitHub release that was generated and Publish it
- This will trigger another AppVeyor build, which will include the publishing of NuGet packages, and notifications to Twitter, Gitter, etc
- Checkout develop branch and merge release branch
- Get a coffee/tea/Irn-Bru/whatever your poison is

Let me know if you have any questions.

**Comment by wwwlicious** [comment]
Oh coffee, definitely coffee! Thanks for the guide, perfect and much appreciated 👍

**Comment by gep13** [comment]
@wwwlicious you are very welcome.  Glad you got it all working!

**Pull request merged**
