### PR TITLE
(#216) upgrade to cake 3.0.0

### LINKED ISSUE #115: Remove references to obsolete Cake members.
> Probably it's because `Cake.Incubator` used in integration tests provides extension methods for `DotNetBuildSettings`.
>
_Originally posted by @devlead in https://github.com/cake-build/cake/pull/2837#issuecomment-688275062_

Or this addin will stop to work when Cake 1.0 is released.

### LINKED ISSUE #216: Update Cake.Incubator add-in to target Cake v3.0.0
This is currently blocked by https://github.com/cake-contrib/Cake.Incubator/pull/215

### PR DESCRIPTION
**Pull request by wgnf**
## Description

changes to made to target new Cake version 3.0.0

## Related Issue

- Closes #216 
- and probably Closes #115
- also related to https://github.com/cake-contrib/Cake.Incubator/pull/215
- also related to https://github.com/cake-contrib/Cake.Incubator/pull/218 (as i had to upgrade this package for this PR)

## Motivation and Context

The motivation of this PR is to keep up development with the current Cake version.  
Also currently `Cake.Incubator` cannot be used in a Cake 3.0.0 build, as stated by this comment: https://github.com/cake-contrib/Cake.Incubator/issues/216#issuecomment-1406585650

## How Has This Been Tested?

- Run all unit-tests in Rider
- Cake.Tool 3.0.0 script
- Cake.Frosting 3.0.0 (with project reference)

### Unit Tests

image

### Cake.Frosting

```cs
[TaskName("Default")]
[IsDependentOn(typeof(TestTask))]
[IsDependentOn(typeof(BuildTask))]
public class DefaultTask : FrostingTask
{
}

[TaskName("Build")]
public class BuildTask : FrostingTask
{
    public override void Run(ICakeContext context)
    {
        var settings = new DotNetMSBuildSettings();
        settings.WithTargets(new[] { "build", "test" });
        
        context.DotNetBuild(@"X:\Dev\git\Cake.Incubator\src\Cake.Incubator\Cake.Incubator.csproj", new DotNetBuildSettings
        {
            MSBuildSettings = settings
        });
    }
}

[TaskName("Test")]
public class TestTask : FrostingTask
{
    public override void Run(ICakeContext context)
    {
        var settings = new XUnit2Settings
        {
            Parallelism = ParallelismOption.None
        };
        
        context.DotNetTest(@"X:\Dev\git\Cake.Incubator\src\Cake.Incubator.Tests\Cake.Incubator.Tests.csproj", settings);
    }
}
```

image
(fails, but it inidicates that the targets have been successfully added to `DotNetBuild` -> so success)

### Cake.Tool script

```cs
#addin nuget:file://X:/Dev/git/Cake.Incubator/src/Cake.Incubator/bin/Debug/?package=Cake.Incubator&version=1.0.0

Task("Default")
    .IsDependentOn("Test")
    .IsDependentOn("Build");

Task("Build")
    .Does(() => 
    {
        var settings = new DotNetMSBuildSettings();
        settings.WithTargets(new[] { "build", "test" });

        DotNetBuild(@"X:\Dev\git\Cake.Incubator\src\Cake.Incubator\Cake.Incubator.csproj", new DotNetBuildSettings
        {
            MSBuildSettings = settings
        });
    });

Task("Test")
    .Does(() => 
    {
        var settings = new XUnit2Settings
        {
            Parallelism = ParallelismOption.None
        };
        
        DotNetTest(@"X:\Dev\git\Cake.Incubator\src\Cake.Incubator.Tests\Cake.Incubator.Tests.csproj", settings);
    });

RunTarget("Default");
```

image
(fails, but it inidicates that the targets have been successfully added to `DotNetBuild` -> so success)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All (new and) existing tests passed.

### CODE REVIEW

**Comment by wgnf** [comment]
i hope i haven't missed anything major as this is my first PR here and quite a major one at that 😄

**Comment by wgnf** [comment]
Everything worked fine for me locally. I was wondering if there is anything else that I could test locally or in any other way?

**Comment by wgnf** [comment]
The duplication that has been found is not from my changes. I guess it's a good change though. Should I change it? (extract that fragment into a new method)

**Comment by nils-a** [comment]
Interesting that this would pop-up now. 😕 

> Should I change it? (extract that fragment into a new method)

Yes, makes sense. Could you extract the *html*-part (right between the two fragments that pop-up as duplications) along with it? (i.e. make the extension a parameter.)

The other changes look good to me. I'll merge it in and pursue a new release once you pushed the modification. Thanks for getting this done.

**Comment by wgnf** [comment]
Yeah true, makes sense.

**Review by nils-a — APPROVED** [review]
Looks good to me. :+1:

**Comment by nils-a** [comment]
@wgnf your changes have been merged. Thanks for getting this done.

**Comment by wgnf** [comment]
with pleasure :)

**Pull request merged**
