### PR TITLE
Bump Cake to 2.0.0

### LINKED ISSUE #170: Update Cake.Incubator add-in to target Cake v2.0.0
[Cake 2.0.0](https://cakebuild.net/blog/2021/11/cake-v2.0.0-released) has been released  🎉

### PR DESCRIPTION
**Pull request by gitfool**
Fixes #170.

### CODE REVIEW

**Comment by gitfool** [comment]
GitVersion is failing with:
```
System.DllNotFoundException: Unable to load shared library 'git2-106a5f2' or one of its dependencies.
```
But this should work since I know `5.8.1` works with `ubuntu-latest` as I use that combo myself. 😖

**Comment by gitfool** [comment]
@gep13 what am I missing? 🤔

**Comment by nils-a** [comment]
@gitfool When I build, there's `Cake.Git` in version 0.22.0 in the addins folder. This uses `LibGit2Sharp-0.26.2` which uses `LibGit2Sharp.NativeBinaries-2.0.306` which provides exactly `git2-106a5f2`.

IMHO the first version of `Cake.Git` to support ubuntu 20.04 is 1.1.0 - which targets Cake 1.0.0 and is currently not supported by `Cake.Recipe`.

**Comment by gitfool** [comment]
@nils-a thanks for the tip! Looks like the `Cake.Git` dependency is coming from `Cake.Issues.Recipe` and that this could be fixed by bumping `Cake.Issues.Recipe` from 0.4.3 to 1.3.2:
* [Cake.Recipe/addins.cake](https://github.com/cake-contrib/Cake.Recipe/blob/9ea449d1868455230dddd236f528edb62cb349ef/Source/Cake.Recipe/Content/addins.cake#L24)
* [Cake.Issues.Recipe/addins.cake](https://github.com/cake-contrib/Cake.Issues.Recipe/blob/0.4.3/Cake.Issues.Recipe/Content/addins.cake#L5) (0.4.3)
* [Cake.Issues.Recipe/addins.cake](https://github.com/cake-contrib/Cake.Issues.Recipe/blob/1.3.2/Cake.Issues.Recipe/Content/addins.cake#L5) (1.3.2)

Not sure but such a bump would probably have to be released in a patched `Cake.Recipe` version 2.2.2 for it to be useable while still building against Cake 1.0.0.

**Comment by gitfool** [comment]
@gep13 @nils-a ready for review after I reverted the github workflow platforms to avoid issues with git native dependencies. 😁

**Review by nils-a — APPROVED** [review]
LGTM!

**Pull request merged**
